allowBuilds:
  '@vercel/speed-insights': true
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - esbuild
  - sharp

overrides:
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
